### ISSUE TITLE
Fix operator precedence

### ISSUE THREAD

**Issue by pvdrz** [pvdrz/pijama_legacy#1]
All the binary operators are left-associative but there is no precedence between them. So the following function wont type well.
```
fn foo(x: Int, y: Int, z: Int) do
     x + y > y - z
end
```
Because it is parsed as `((x + y) > y) - z` instead of `(x + y) > (y - z)`. I don't have an strong opinion about having precedence between arithmetic operations. But I think that at least the precedence should be
```
(+, -, *, /, %) < (<=, >=, <, >, ==, !=) < (&&, ||)
```
So `x + y > 0 && z > x + y` should be parsed as `((x + y) > 0) && (z > (x + y))`

**Comment by tech6hutch** [comment]
Having equal precedence for + and * will be confusing. If you don't want * to bind tighter than +, then you should probably disallow mixing them without grouping parentheses.

**Comment by pvdrz** [comment]
> Having equal precedence for + and * will be confusing. If you don't want * to bind tighter than +, then you should probably disallow mixing them without grouping parentheses.

Well at this point I suppose is better to do the whole thing if precedence is going to be introduced.

**Comment by christianpoveda** [comment]
I believe this should be a valid testcase: 
```
def loop() do
    if false do
        true
    else
        loop()
    end
end
true || loop()
```
should return `true` without diverging.
