### ISSUE TITLE
Add useful information to type errors

### ISSUE THREAD

**Issue by pvdrz** [pvdrz/pijama_legacy#10]
WIth the exception of parsing errors. All the errors in the language don't make reference to the code where the error is happening. 

This is particularly important for type errors which are the most common kind of error in the language. I think [annotate-snippets-rs](https://github.com/rust-lang/annotate-snippets-rs) is a reasonable crate for achieving this. 

In order to generate useful errors we need to:
- [ ] Recover the location of each token using `nom_locate`.
- [ ] Store the location of each node in the AST.
- [ ] Figure out how to transfer the location of each node during lowering (type-checking is done over the MIR).
- [ ] Build a suitable representation of each error variant using annotate-snippets-rs.

**Comment by seanchen1991** [comment]
I'm not familiar with `nom`. Does it provide the ability to pull out the location of each parsed token when it processes the input string, or would that logic have to be added to the `parse` methods for each type?

**Comment by pvdrz** [comment]
I've been looking for that functionality in `nom` and I didn't find anything. Another parser combinator library `combine` has a [combinator](https://docs.rs/combine/4.1.0/combine/parser/token/fn.position.html) for that.

Even then, I think we could start working on changing the structures themselves to store that information and then figure out if `nom` can provide the location or if we need to change the parser module.

**Comment by pvdrz** [comment]
@Geal, is it there any way to get the span of the output produced by a parser in `nom`?

PD: I hope it doesn't bother you that I'm @ ing you like that

**Comment by DarkDrek** [comment]
From the nom readme
> nom will get you started quickly with powerful custom error types, that you can leverage with [nom_locate](https://github.com/fflorent/nom_locate) to pinpoint the exact line and column of the error.

Did you already looked into this?

**Comment by pvdrz** [comment]
> Did you already looked into this?

No I haven't, and that's exactly what we need! Thanks!
