### ISSUE TITLE
Bit operations for numbers

### ISSUE THREAD

**Issue by DarkDrek** [pvdrz/pijama_legacy#17]
Should this language support bit operations on numbers like BitAnd, BitOr, BitXor?

Checklist:
- [x] Modify the parser to support `&` `|` and `^` and add them as variants of `BinOp`. 
- [x] Add some tests to check that there is no conflict between parsing the new operators and `&&` and `||`.
- [x] Include the new operators in the type checking rule for other integer operators.
- [x] Update `eval_bin_op` inside the `lir` module to evaluate the operations using the Rust's ones.
- [ ] (Optional) Drop a comment in https://github.com/christianpoveda/pijama/issues/1 to address operator precedence.

**Comment by pvdrz** [comment]
I don't see any reason to say it shouldn't. Do you want to implement them?

**Comment by DarkDrek** [comment]
I want to implement them.

**Comment by pvdrz** [comment]
Great. I'll edit the first comment and add an small checklist so we can track progress

**Comment by DarkDrek** [comment]
I think this is done (besides the optional point about precedence) so it can be closed?

**Comment by pvdrz** [comment]
closed via https://github.com/christianpoveda/pijama/pull/21
