### ISSUE TITLE
Infer the types of `==` and `!=`

### ISSUE THREAD

**Issue by pvdrz** [pvdrz/pijama_legacy#2]
Pijama's type system doesn't have universal polymorphism. Which means that `+:  Int -> Int -> Int` and `>: Int -> Int -> Bool`. 

For most operators it is not a big deal because `+, -, *, /, %` are operators over the integers and `&&, ||` are operators over booleans. So don't intend to make any sense of `true + true` or `0 || 0`.

However, for `==` and `!=` the issue is different, `true == true` and `1 == 1` are both valid operations that could be useful for writing some programs. The typing rule for them would be something like

```
Γ ⊢ x: T, y: T with T = Bool | Int
──────────────────────────────────
Γ ⊢ (x == y): Bool
```
and the same for `!=`.

**Comment by seanchen1991** [comment]
I'd like to take a stab at this. 

Looking at the relevant code in `ty_check.rs` to implement this, it seems like we'll need to return either 
```
Ty::Arrow(
    Box::new(Ty::Int), 
    Box::new(Ty::Arrow(Box::new(Ty::Int), Box::new(Ty::Bool))
)
```
or 
```
Ty::Arrow(
    Box::new(Ty::Bool), 
    Box::new(Ty::Arrow(Box::new(Ty::Bool), Box::new(Ty::Bool))
)
```
depending on the arguments to the equality operator. But I'm unsure of how best to go about figuring out the types of the arguments to the operator in this case. 

One thought that did occur to me is to the treat `==` and `!=` as a different type of `Abstraction`, not having them count as the typical binary operations, but that seems a bit overkill and there's probably a more straightforward way of doing this that I'm not seeing.

**Comment by pvdrz** [comment]
Hi!

Those are exactly the types that `==` and `!=` must have and I agree with you, I haven't find a completely satisfactory way to fix this.

What I think works best right now is to do something like this:
- If there is a term with the form  `((== t1) t2)` we know that it must have a `Bool` type.
- Then if `t2` has type `T`, that means that `(== t1)` must have type `T -> Bool`.

In conclusion, any term of the form `(== t)` must have type `T -> Bool` where `T` is the type of `t`. 

We could add this new behavior inside `type_of` in the `Term::App(t1, t2)` branch. If  `t1` is something like `App(Abs::Binary(Equal), t3))` (which is the representation of `(== t3)`) then the type of `t1` must be `Arrow(type_of(t3), Bool)` instead of calling `type_of(t1)`.

Let me know what you think about this approach.

**Comment by seanchen1991** [comment]
So what that makes me think is: 
In the `Term::App(t1, t2)` branch, match on `t1` to determine whether it matches `Abs::Binary(Equal)` before we determine the type of `t1`?

Is there a better way to handle that besides a bunch of nested matches at the top of the `Term::App` branch? Seems like a very sub-par way of doing it, especially with all of the duplicated logic.

**Comment by pvdrz** [comment]
Maybe you could do a new branch `Term::App(Term::Abs(Abstraction::Binary(BinOp::Equal)))` above the `Term::App(t1, t2)` one.

This makes me think that there should be an easier syntax to write this kind of stuff...

**Comment by seanchen1991** [comment]
I wasn't able to get your suggestion to work 😞

I think this bug points to a structural issue. Ideally, binary operations wouldn't care about the actual types of their args, they only need to care that their args match in type. With the recursive nature of the tree-walking implementation of `type_of`, it's difficult to perform any sort of look-ahead to check that the types match for some expression `((== t1) t2)` without re-working the entire approach, I think.

**Comment by pvdrz** [comment]
> Ideally, binary operations wouldn't care about the actual types of their args, they only need to care that their args match in type. 

I agree with you but doing that would require having some form of polymorphism and sadly we aren't there yet.

> With the recursive nature of the tree-walking implementation of `type_of`, it's difficult to perform any sort of look-ahead to check that the types match for some expression `((== t1) t2)` without re-working the entire approach, I think.

Maybe I wasn't able to make myself clear. My suggestion was to change [this](https://github.com/christianpoveda/pijama/blob/32095a50c6e6b6b63b4266511c2f969acca737cc/src/ty_check.rs#L78) line to something like
```rust
// if inside the `(t1 t2)` term, `t1` = `(== t3)` for some `t3`, 
// then `t1` has type `T -> Bool` where `T` is the type of `t3`.
// Otherwise compute the type of `t1` doing the normal traversal.
let ty1 = if let Term::App(box Term::Abs(Abstraction::BinaryOp(BinOp::Equal)), t3) = t1 {
    Ty::Arrow(Box::new(self.type_of(t3)?, Box::new(Ty::Bool)))
} else {
    self.type_of(t1)
}
```

**Comment by seanchen1991** [comment]
Got it, that clears things up for me 👍 
Looks like I got it working on my end. I'll go ahead and submit a PR for this tomorrow.

**Comment by pvdrz** [comment]
> Got it, that clears things up for me +1
> Looks like I got it working on my end. I'll go ahead and submit a PR for this tomorrow.

Awesome! I know right now the code is a mess but I'll try to add some love and docs to it soon.

**Comment by pvdrz** [comment]
Oh I almost forgot. Could you throw an error if the type of `t3` is an arrow? Deciding if two functions are equal goes beyond the scope of this issue. 

Edit: I think none of the variants in `TyError` is adequate for this. Maybe we need a new variant called `NotBasicTy` or something like that.

**Comment by pvdrz** [comment]
closed via https://github.com/christianpoveda/pijama/pull/6
