### ISSUE TITLE
Add tests for type checking

### ISSUE THREAD

**Issue by pvdrz** [pvdrz/pijama_legacy#20]
This issue is tracking the coverage of the test suite for the type-checker:

- [x] Check that literals match their own type.
    - [x] `true` and `false` must be `Bool`s.
    - [x] `unit` must be `Unit`.
    - [x] numbers must be `Int`.
- [x] Check that functions have type `T -> U` where `T` is the type of the argument and `U` the type of the return.
- [x] Check  binary operations:
    - [x] Check that binary operations are rejected if the terms doesn't have the same type.
    - [x] Check that arithmetic operations have type `Int`.
    - [x] Check that arithmetic operations only work with integers.
    - [x] Check that boolean operations have type `Bool`.
    - [x] Check that boolean operations only work with booleans.
    - [x] Check that integer comparison operations have type `Bool`.
    - [x] Check that integer comparison operations only work with integers.
    - [x] Check that equal and not equal have type `Bool` for every base type.
- [x] Check unary operations:
   - [x] Check that arithmetic operations have type `Int` and only work with integers.
   - [x] Check that boolean operations have type `Bool` and only work with booleans.
- [x] Check function calls (applications):
   - [x] Check that `f(x)` has type `U` if `f` has type `T -> U` and `x` has type `T`.
   - [x] Check that `f(x)` is rejected if `f` has type `T -> U` and `x` has a type different from `T`.
- [x] Check bindings:
   - [x] Check that `x = y` actually enforces that `x` has the same type as `y`.
- [x] Check conditionals:
   - [x] Check that `if x do y else z end` has type `T` if `y` and `z` have type `T` and `x` has type `Bool`.
  - [x] Check that `if x do y else z end` is rejected if `y` and `z` have different types.
  - [x] Check that `if x do y else z end` is rejected if `x` is not a boolean.
- [x] Check ignored terms
- [x] Check recursive functions

Update: If you're new to the project and want to tackle one of these items. Ping @christianpoveda asking for mentoring instructions :)

**Comment by pvdrz** [comment]
@DarkDrek this is a lot but it should give you an idea of what you can cover. Thanks for the help!

**Comment by DarkDrek** [comment]
For things like "Check that arithmetic operations have type Int and only work with integers." we probably want to check all operators or is it ok for now to just write 1 test case for 1 operator?

**Comment by pvdrz** [comment]
> For things like "Check that arithmetic operations have type Int and only work with integers." we probably want to check all operators or is it ok for now to just write 1 test case for 1 operator?

I think we can add one for now and then figure out if we can apply the same test for several files.

**Comment by pvdrz** [comment]
@DarkDrek which ones can be checked now after the ones you added?
