### ISSUE TITLE
Rename binary operators

### ISSUE THREAD

**Issue by pvdrz** [pvdrz/pijama_legacy#26]
Inside the `ast` module we have the `BinOp` type which represents binary operations in all the internal representations. However, the name of the variants are too verbose and we could rename them:

```rust
pub enum BinOp {
    Plus, // Change to `Add`
    Minus, // Change to `Sub`
    Times, // Change to `Mul`
    Divide, // Change to `Div`
    Modulo, // Change to `Rem`
    And, // This is fine
    Or, // This is fine
    BitAnd, // This is fine
    BitOr, // This is fine
    BitXor, // This is fine
    Equal, // Change to `Eq`
    NotEqual, // Change to `Neq`
    LessThan, // Change to `Lt`
    GreaterThan, // Change to `Gt`
    LessThanOrEqual, // Change to `Lte`
    GreaterThanOrEqual, // Change to `Gte`
}
```
This should be relatively straightforward to do and should give you a good tour around the codebase if you are interested :)

**Comment by seanchen1991** [comment]
Still learning my way around the codebase, so I will gladly take an opportunity to tour all the different parts of it 😄

**Comment by DarkDrek** [comment]
I never seen `Leq` and `Geq` as abbreviations... what about? 
```
LessThanOrEqual, // Change to `Lte`
GreaterThanOrEqual, // Change to `Gte`
```

**Comment by pvdrz** [comment]
> I never seen `Leq` and `Geq` as abbreviations... what about?
> 
> ```
> LessThanOrEqual, // Change to `Lte`
> GreaterThanOrEqual, // Change to `Gte`
> ```

They are equally long so it sounds good to me. I'll update the first comment to reflect that.

**Comment by pvdrz** [comment]
closed via https://github.com/christianpoveda/pijama/pull/43
