### ISSUE TITLE
Add syntax for anonymous functions

### ISSUE THREAD

**Issue by pvdrz** [pvdrz/pijama_legacy#33]
Pijama's IRs have no problem handling anonymous functions, but there is not a node in the AST for that. 

We need to:
- [x] figure out which syntax to use. 
    ```
    fn(x: Int) do x + 1 end
    ```
- [ ] modify the parser to support such syntax.
- [ ] add the new node variant to the AST.
- [ ] fix the lowering between the AST and the MIR.
- [ ] add tests for:
    - [ ] parsing
    - [ ] typing
    - [ ] evaluation

**Comment by pvdrz** [comment]
I have the following candidates for the syntax:
- Haskell's lambda syntax: `(\x: Int -> x + 1)`
- Rust's closures (with `do`/`end` body): `|x: Int| do x + 1 end`
- Python's lambda syntax: `lambda x: Int do x + 1 end`

**Comment by DarkDrek** [comment]
My personal favorite is the rust syntax. But how about:
- Elixir like `fn(x: Int) -> do x + 1 end`

**Comment by pvdrz** [comment]
> But how about:
>
>     * Elixir like `fn(x: Int) -> do x + 1 end`
I like how it looks. My only "complain" is that we'd need to do an additional look-ahead during parsing to differentiate a function definition from an anonymous function. Something like: "if ahead we have `fn` and then a name, that's a function definition. Otherwise, it is a lambda". On the other hand I really like the syntax consistency (f we drop the arrow) because we'd have
```
fn foo(x: Int) do x end
```
and 
```
foo = fn(x: Int) do x end
```
actually meaning the same thing.

**Comment by DarkDrek** [comment]
If we require the brace directly after `fn` we could differentiate between `fn ...` with space and `fn(...`
I'm fine with dropping the arrow.

**Comment by pvdrz** [comment]
actually the space is not much of a deal. So it seems we have a winner for the abstraction syntax :D. thanks

**Comment by DarkDrek** [comment]
Do we want to have recursive anonymous functions? The only way I see it working would be some special name referring to the current function like `self`. This may change how #36 can be solved.

**Comment by pvdrz** [comment]
> Do we want to have recursive anonymous functions?

I'm inclined to say we don't. Do you have any case of use where you need a short-lived recursive function? Otherwise I think regular functions can fill that gap perfectly.

**Comment by DarkDrek** [comment]
I don't have a use-case but it just seems to be a common but arbitrary restriction (a google search didn't bring up much).

**Comment by pvdrz** [comment]
I have a conspiracy theory about it. Probably using `self` or any other keyword feels too much like OOP and functional programmers feel dirty using it :P
