### ISSUE TITLE
Consider adding lists

### ISSUE THREAD

**Issue by pvdrz** [pvdrz/pijama_legacy#35]
Pijama doesn't have a way to store collections of values, limiting what we can write in it. A quick win for this would be to add lists to the language. There are two paths we can take here
- Implement lists as a native type: Just as integers and booleans, We'd have a new type `List<T>` or `List[T]` to represent lists and all the operations over list would be built-in operations.
- Wait until we get algebraic data types: If we implement ADTs first, we can implement lists as a library instead of as a language built-in construct.

The advantages of the first path are:
- We can do it now.
- It will have a better performance than the ADT approach.
The disadvantages are:
- This increases the complexity of the evaluator, type checker and IRs just to add lists.
- This might open the path to implementing all the collections as built-in constructs and having no chance of implementing performant collections in the language itself.

**Comment by seanchen1991** [comment]
Who doesn't love algebraic data types? 😄 
That being said, performance is definitely an important consideration for a language like this; I'm sure we'd want lists to be as performant/light weight as possible. 

I think I still lean slightly towards ADTs, but that's just me.

**Comment by pvdrz** [comment]
I also like ADTs because they let you encode a lot of information in the type system and I want to get there eventually. I was checking what other languages do here and here is the result:
- Python: Lists are implemented as arrays in`C`.
- Elixir: Uses Erlang's lists which are linked lists implemented in `C`.
- Haskell: Lists are regular datatypes.
- OCaml: I couldn't find anything but I'm under the impression that they are also regular datatypes.

**Comment by seanchen1991** [comment]
Haskell and OCaml implementing lists as regular datatypes are interesting data points. Does that add some points in favor of implementing them as regular datatypes in Pijama for you?

**Comment by pvdrz** [comment]
After discussing it with my pillow, I think ASTs are a better idea in general. 

This is just a personal opinion but languages should feel open and powerful even if there are some performance compromises here and there. And this openness including being able to write your own alternative implementation of a list if you don't like the one the language currently has and be able to match its performance.

There are great languages with top performance out there and we aren't competing with those.

**Comment by seanchen1991** [comment]
Is there anything blocking us from implementing algebraic data types at this point?

**Comment by pvdrz** [comment]
Mmm... I wouldn't say there is anything blocking it really. We just need to figure out how ADTs look in each compilation stage. After we close the other features we have dangling. We can start thinking how they should look.

I think I'm closing this one as it seems it is a better idea to wait for ADTs.
