### ISSUE TITLE
Add bit shifting operators

### ISSUE THREAD

**Issue by pvdrz** [pvdrz/pijama_legacy#37]
Bit-shift operators are useful to implement several integer functions (such as hashing functions). We just have to expose them as binary arithmetic operations inside Pijama. The tasks are the following:
- [x] Add two variants `Shl` and `Shr` to the `BinOp` type inside the AST module . 
- [x] Update the parser being sure that:
  - [x] `<<` is `Shl` and `>>` is `Shr`.
  - [x] They have the same precedence as `&`, `|`, and `^` (@DarkDrek what do you think?)
  - [x] There is no conflict with `>` and `<` (check how `&` and `&&` are parsed to have an idea)
- [x] Include the new operators in the type checking rule for the arithmetic operators.
- [x] Update `native_bin_op` inside the `lir::eval` module to evaluate the operations using their Rust equivalents.

**Comment by DarkDrek** [comment]
I'm doing this right now :smile:! 
They should have the same precedence as the other bit operations.

**Comment by pvdrz** [comment]
closed via https://github.com/christianpoveda/pijama/pull/38
