### ISSUE TITLE
Make boolean operators short-circuiting

### ISSUE THREAD

**Issue by pvdrz** [pvdrz/pijama_legacy#4]
The evaluation of a program like 
```
x = false
true || x
```
is done by replacing `x` inside `true || x` and then actually doing the `||` operation. We could avoid the substitution by evaluating `true || x` to `true` directly because the value of `x` does not matter here.

An easy way to do this is to change the `step` method inside `lir.rs` and  change the branch that takes care of binary operators to do the following:
- if the operator is `||` and one of the terms is `true`, evaluate to `true`.
- if the operator is `&&` and one of the terms is `false`, evaluate to `false`.

**Comment by seanchen1991** [comment]
In this case, are you talking about not getting to the match on `t2` to see if it's a `Literal` on line 140, or do you mean not executing `eval_bin_op` on line 142 when you're talking about making boolean operators short-circuiting?

**Comment by pvdrz** [comment]
That's a good question. Sadly I think we cannot do this change as straightforward because we might need to short circuit using the first term or the second. So that means we must touch two branches.

if we are dealing with a term like `((op a) b)` i think the evaluation should happen as follows:
```rust
Term::App(
    box Term::App(box Term::Abs(Abstraction::Binary(op)), box Term::Lit(l1)),
    box t2,
) => {
    if let Term::Lit(l2) = t2 {
        // old behavior, i.e. do the operation
    } else {
        // try to short-circuit using `l1`, else do t2.step()
    }
}
Term::App(box Term::Abs(abs), box t2) => match abs {
    ...
    // we only get here if in the term `((= a) b)`, `a` wasn't a literal,
    // then `b` is the only option for short circuiting
    Abstraction::Binary(op) => {
        // try to short-circuit using `t2`, else do t2.step()
    }
},
```
what do you think? 

Edit: maybe it is easier to just add a whole new set of branches before these two with the complete information?
```rust
Term::App(
    box Term::App(box Term::Abs(Abstraction::Binary(BinOp::And)), box Term::Lit(Literal::False)) _ ,
) => // evaluate to false
Term::App(
    box Term::App(box Term::Abs(Abstraction::Binary(BinOp::And)), _) box Term::Lit(Literal::False ,
) => // evaluate to false
...
```
and so on.

Edit 2: IDK neither solution makes me happy tbh. Maybe we should change the whole evaluation scheme to be more flexible when testing patterns of terms. This whole `step` method with a bunch of patterns is becaming un(readable + maintainable).

**Comment by seanchen1991** [comment]
Agreed that it is a bit messy and hard to re-work. So you're thinking we shelve this particular issue in favor of refactoring the entire evaluation scheme as per #9 ?

**Comment by pvdrz** [comment]
yes I'd think that would be better

**Comment by pvdrz** [comment]
It would be nice if there could be an evaluation test for this behavior. A program like
```
def loop() do
    if false true else loop() end
end
true || loop()
```
Should return `true` without diverging

**Comment by pvdrz** [comment]
I believe this should be a valid testcase: 
```
def loop() do
    if false do
        true
    else
        loop()
    end
end
true || loop()
```
should return `true` without diverging.

**Comment by pvdrz** [comment]
Closed via https://github.com/christianpoveda/pijama/pull/23
