### ISSUE TITLE
Add comments to parser functions

### ISSUE THREAD

**Issue by DarkDrek** [pvdrz/pijama_legacy#40]
Some function in `parser.rs` have rather cryptic names and the exact calling order is not immediately visible.
So it would be the best to have a comment at the top explaining the overall structure and at least one comment per function explaining what the function will try to parse.
Some function may also benefit from comments on individual nom function calls.

PS: Maybe splitting the parse functions in different parser sub-modules could also help?

**Comment by pvdrz** [comment]
> Some function in `parser.rs` have rather cryptic names and the exact calling order is not immediately visible.

yes totally, it needs a little bit of order

> So it would be the best to have a comment at the top explaining the overall structure and at least one comment per function explaining what the function will try to parse.

> Some function may also benefit from comments on individual nom function calls.

Will do


> 
> PS: Maybe splitting the parse functions in different parser sub-modules could also help?

Sounds good. I'll add it to my list :)
