### ISSUE TITLE
Add a print built-in function

### ISSUE THREAD

**Issue by pvdrz** [pvdrz/pijama_legacy#44]
It would be nice to have a function able to print values available. However, there are several things that need to be sorted out first:
- [x] What should be the name of the function?  (`print` was our choice)

  `print` and `puts` are the first two options that come to mind.
- [x] What should be the type of such function?  (`T -> Unit` was our choice)

    I think it is too soon to start worrying about the fact that printing is a fallible operation (so no effects for now). The two options I can think of are:
   -  `T -> Unit`: The function consumes the term to be printed.
   -  `T -> T`: The function returns the term after printing it.
   

- [ ] What can be printed? 
    
    The argument of the function should be evaluated to print it, but the evaluation could end in a function or any other term that is not a literal. There is no way to recover the AST representation of terms so we'd have to show the LIR of the term.

Update: Even though we still have to decide what can be printed. We can start working towards an implementation of this once https://github.com/christianpoveda/pijama/issues/54, https://github.com/christianpoveda/pijama/issues/55 and https://github.com/christianpoveda/pijama/issues/56 are resolved.

The steps we need to take are:
- [ ] add a new `Print` variant to `ast::Primitive`.
- [ ] add the `stdout` stream to `Machine`.
- [ ] change the `Machine::step_primitive_app` to print stuff using the stream.
- [ ] update `ty::ty_check` to inspect terms with the pattern
    ```rust
    Term::App(Term::PrimitiveFn(Primitive::Print), t1)
    ```
    and assign them the type `Unit`.
- [ ] Fix parsing by adding a new `parser::primitive` module to produce `Primitive` elements (more instructions soon).

**Comment by DarkDrek** [comment]
I think `print` is good name for printing to the default console. `puts` sounds to much like C 😄.
Do we restrict the inbuilt function to only print to std-out or do we need variants for other output channels?

I would start with `T -> Unit` because it seems easier to reason about it as the first built in function.

**Comment by pvdrz** [comment]
`print` is good for me too, I put `puts` under consideration just because Ruby and Elixir are a large influence in terms of syntax here :P

I think stdout is fine for now. Maybe in the future we can add an `eprint` or something like that where we back both functions with a new built-in able to write to each channel via a parameter.

**Comment by pvdrz** [comment]
@DarkDrek have you started working on something else now? I'd like to merge https://github.com/christianpoveda/pijama/pull/49 but I don't want to disrupt your workflow with it.

**Comment by DarkDrek** [comment]
Merge your PR I have currently nothing that would be disrupted through it. I would start working on another issue after the merge.

PS: good (git) luck with the merge 🤓

**Comment by pvdrz** [comment]
Hahaha it's going to be a hard one. I'll wait for Sean to see if I can merge it without causing a wreck.

**Comment by pvdrz** [comment]
@DarkDrek I think we are ready for this. Do you want to do the honors?

**Comment by pvdrz** [comment]
Closed via #72
