### ISSUE TITLE
Fix parsing errors

### ISSUE THREAD

**Issue by pvdrz** [pvdrz/pijama_legacy#48]
This is something I've been postponing because I'm not even sure how to tackle it. 

I think Pijama's parser is relatively well documented. However, users don't read the docs of the parser to understand why their programs don't compile.

For example, this program
```
fn foo(x: Int) doo
    x
end

foo(10)
```
cannot be parsed because of the extra `o` and the parsing error is:
```
0: at line 1, in MultiSpace:
fn foo(x: Int) doo
                 ^
```
Which has the error in the right position but there is no explanation or suggestion on how to fix it. My first impression would be to say something like "wtf is `MultiSpace`?"

Another funny example is if someone tries to use a keyword as a function name:
```
fn unit(x: Int) do x end
   ^
expected '(', found u
```
Again, the parser is right but the `(` suggestion is less than helpful.

I think that we need some sort of custom errors that play well with nom, because nom already has the correct position for most of the errors. We just need to write certain critical sections of the parser to be more clear when they fail.

I think it would be good to follow the same idea as in https://github.com/christianpoveda/pijama/issues/10 and use annotate-snippets-rs to display the errors. In that way we can share most of the code for both kind of errors.

Update: Errors now look better but the information is the same. We should investigate how to add custom error types to nom to be able to add new information when certain parsers fail.

**Comment by DarkDrek** [comment]
I want to have a go at this.

**Comment by pvdrz** [comment]
how do you want to tackle it?

**Comment by DarkDrek** [comment]
> how do you want to tackle it?

The simplest way by adding some context to possible errors where we know that something is coming. Look at PR #67

**Comment by pvdrz** [comment]
I think we can mark this as done for now as https://github.com/christianpoveda/pijama/pull/67 solves most of the pains I stated here. Future improvements deserve their own issue as they can be more specific.
