### ISSUE TITLE
Move evaluation to its own structure

### ISSUE THREAD

**Issue by pvdrz** [pvdrz/pijama_legacy#55]
Right now most of the evaluation happens inside the `lir` and `lir::eval` modules and it is completely stateless.

However in the future we might require to store state (for call-by-need evaluation or interact with the outside world). So it would be better to have a single `Machine` structure to take care of all the evaluation.

For this we need to:
- [x] Create a new top-level module `machine`.
- [x] Create an empty (for now) `Machine` structure.
- [x] Move the `lir::Term::step`, `lir::Term::step_inplace`, `lir::Term::evaluate` and all the functions inside `lir::eval` to the `machine` module and change them to be methods of `Machine`. 
- [ ] Add a `machine::evaluate` public function that takes a `Term`, creates a new `Machine` and evaluates the term using the new `Machine::evaluate` method.
- [x] Plug this `machine::evaluate` function into the `run` method at the top of the library.

For example the `lir::Term::step` method looks like this
```rust
impl Term {
    ...
    fn step(mut self) -> (bool, Term) { ... }
}
```
after these changes it should look like this
```rust
impl Machine {
    ...
    fn step(&mut self, mut Term) -> (bool, Term) { ... }
}
```

**Comment by DarkDrek** [comment]
I will extract my `Machine` struct from #47, remove unnecessary things will provide it as new PR if its ok?

**Comment by pvdrz** [comment]
Sounds great! Thanks! Keep it minimal though

**Comment by pvdrz** [comment]
closed via https://github.com/christianpoveda/pijama/pull/57
