### ISSUE TITLE
Add AST support for primitive functions

### ISSUE THREAD

**Issue by pvdrz** [pvdrz/pijama_legacy#56]
To support functions like `print` which interact with the outside world we need to have a way to distinguish them from the regular functions we have in the language.

One way to do this is to add a new node to the AST for primitive/built-in functions. Such that calls to these functions trigger a particular method inside `Machine` (See https://github.com/christianpoveda/pijama/issues/55).

One prerequisite to fully implement this is that the AST must support arbitrary function calls (https://github.com/christianpoveda/pijama/issues/54) to allow the new primitive nodes in the function position. So we won't take care of the parsing part in this issue.

After https://github.com/christianpoveda/pijama/issues/55 is solved. We need to
- [ ] Add a new enum `Primitive` (or `BuiltIn`) with no variants for now.
    - [ ] Add a new `PrimitiveFn` (or `BuiltInFn`) variant to the `ast::Node` enum containing the above type.
    - [ ] Add a new `PrimitiveFn` (or `BuiltInFn`) variant to the `mir::Term` enum containing the above type.
    - [ ] Add a new `PrimitiveFn` (or `BuiltInFn`) variant to the `mir::Term` enum containing the above type.
- [ ] Add a new `mir::lower_primitive` (or `mir::lower_built_in`) method to transform the `Node::PrimitiveFn` variant to a `mir::Term::PrimitiveFn`.
- [ ] Update `ty::ty_check` to return `todo!()` when matching a `Term::PrimitiveFn`.
- [ ] Change the `lir::ctx::Context::remove_names` method to transform the `mir::Term::PrimitiveFn` variant to a `lir::Term::PrimitiveFn`.
- [ ] Add a new `Machine::step_primitive_app` method to handle terms with the pattern
    ```rust
    Term::Abs(box Term::PrimitiveFn(_), box t1)
    ```
    which returns `todo!()` for now.
- [ ] Dispatch the method above inside `Machine::step`.

**Comment by pvdrz** [comment]
#54 and #55 are resolved by now. @DarkDrek do you want to take care of this one? or do you prefer that I take it?

**Comment by DarkDrek** [comment]
You can do it. I'm still working on #67
