### ISSUE TITLE
Add a test suite

### ISSUE THREAD

**Issue by seanchen1991** [pvdrz/pijama_legacy#7]
Would be great to add tests so that it would be easy for contributors to check if changes they introduced break other functionality.

**Comment by pvdrz** [comment]
I was thinking exactly that when I was checking your PR. Let me see what could be a good way of doing it

**Comment by pvdrz** [comment]
I've merged https://github.com/christianpoveda/pijama/pull/8 which adds some basic tests for parsing and a basic Travis CI configuration. Even then we need
- [ ] Tests for lowering between the IRs
- [ ] Tests for type checking (tracked by https://github.com/christianpoveda/pijama/issues/20)
- [x] Tests for evaluation (added in https://github.com/christianpoveda/pijama/pull/11)

**Comment by pvdrz** [comment]
Maybe we can ditch the lowering tests for now? I feel that we'll change the IRs a lot so keeping them up to date will be a lot of work.

**Comment by seanchen1991** [comment]
Gonna close this issue since plenty of tests have been added since I opened it. The tests aren't comprehensive of course, but the ones that have been added certainly addressed the reason for why I initially opened this.

**Comment by pvdrz** [comment]
Thanks! I think we can open individual issues for the remaining untested parts of the project :)
