### ISSUE TITLE
Support comments

### ISSUE THREAD

**Issue by seanchen1991** [pvdrz/pijama_legacy#81]
Would we want to go with `//` or `#` (or something else?) to denote a commented-out line?

Personally, I do think it’s nice that `#` is one fewer key press compared to `//`.

**Comment by DarkDrek** [comment]
> Personally, I do think it’s nice that # is one fewer key press compared to //.

On my keyboard it's even more `#` single press `//` is `shift + 7 + 7 `
Alternatives from [wikipedia](https://en.wikipedia.org/wiki/Comparison_of_programming_languages_(syntax)#Comment_comparison)
- ⍝
- ;
- *>
- $!
- %
- @
- '

PS: 🦙 this unicode llama

**Comment by pvdrz** [comment]
We should use the llama. Close the issue plz.





Hahaha just kidding. I like `#` too, is shorter/easier to type. I think we also need to figure out where do we want those comments. For a first implementation we could have single line comments such that
```elixir
# this comment is ok
1 + 2 # this is not
```
and then we can go back to the end of line comments.

What do you think?

**Comment by DarkDrek** [comment]
I don't mind the `#` and just single full line comments. 
We throw them away during parse or?

@seanchen1991 Do you want to implement this?

**Comment by pvdrz** [comment]
> I don't mind the `#` and just single full line comments.
> We throw them away during parse or?

Yes we ignore them during parsing.

**Comment by seanchen1991** [comment]
Sure, I’ll work on this.

**Comment by seanchen1991** [comment]
#89 also mentions this, but basically:

> Adding comments turns out to be more difficult than we initially thought with how the parser is structured. TL;DR of why it's hard is that there are a bunch of disparate locations in the parser that we'd have to check for comments; there isn't a single centralized location where we can add the comment parser and have it just work as expected (which is how I initially naively imagined it).

So next up is adding support for comments in any kind of context, not just when parsing blocks in particular.

**Comment by pvdrz** [comment]
fixed via #112. Including end-of-line comments
