### ISSUE TITLE
Parse hexadecimal and binary integers

### ISSUE THREAD

**Issue by pvdrz** [pvdrz/pijama_legacy#83]
We only support decimal integers now. However, in certain contexts it is clearer to write `0xff` or `0b11` instead. To solve this issue we need to:
- [x] Figure out the syntax:
    - do `0x10` and `0X10` mean the same? are they both valid?
      _A:_ we'll support lowercase digits only.
    - what happens with the `-`? is processed as usual and just flips the sign of the number?
      _A:_ I think that it should be equivalent to the decimal counterpart: `-0xa == -10` 

- [x] Write 3 new parsers  `hex_number`, `bin_number` and `oct_number` inside `parser::literal`.

    Those parsers should detect and consume the `0x`, `0b` or `0o` prefix but discard it. Leaving just the actual digits of the number and then use [from_str_radix](https://doc.rust-lang.org/std/primitive.i64.html#method.from_str_radix) to convert them to `i64`s.

- [x] Add some parsing and evaluation tests. Stuff like `2 == 0b10` and so on.

**Comment by DarkDrek** [comment]
> One problem here is that there is no method in std to produce a i64 from an string like 0x42f23a.

What about `from_str_radix` https://doc.rust-lang.org/std/primitive.i64.html#method.from_str_radix ? We would just need to remove the `0x` while parsing.

**Comment by pvdrz** [comment]
That sounds great :) I'll update the instructions to reflect that

**Comment by DarkDrek** [comment]
If we use this method we could invent a integer syntax with arbitrary (2-36) integer base. For example `BASE_n_NUMBER`

**Comment by pvdrz** [comment]
how standardized is the syntax for bases different from 2, 8, 10 and 16?

**Comment by DarkDrek** [comment]
As far as I know there aren't other syntaxes for other bases because they aren't used/useful.
We can make our own syntax [xkcd](https://xkcd.com/2309/) 😃

**Comment by pvdrz** [comment]
I feel personally attacked by that comic. 

I think we are OK with decimal, binary and hexadecimal for now.  I'd like to keep syntax as minimal as possible.

**Comment by DarkDrek** [comment]
> I feel personally attacked by that comic.

Sorry for that 🙏 

So for the syntax there is as far as I now (just lower case for now)
- `0xNUMBER` for hex
- `0bNUMBER` for binary
- `0NUMBER` for octal

I propose using `0cNUMBER` for octal to make parsing easier and equal for all special cases.

**Comment by pvdrz** [comment]
> Sorry for that 🙏 

Heh, no problem. I was joking. Sometimes I forgot that text doesn't have the tone I have when talking :P

> I propose using `0cNUMBER` for octal to make parsing easier and equal for all special cases.

what about `0o` like rust? https://doc.rust-lang.org/std/fmt/trait.Octal.html

**Comment by DarkDrek** [comment]
> what about 0o like rust? https://doc.rust-lang.org/std/fmt/trait.Octal.html

The o is very similar to 0 in some fonts but it is still fine if we decide to just take lower case letters (`0O` / 0O won't be readable).

**Comment by pvdrz** [comment]
I think lowercase is good then

**Comment by DarkDrek** [comment]
I will try to implement this then if it's ok.
Can you edit the first post based on the discussion?

**Comment by pvdrz** [comment]
I updated the issue to reflect the current state
