### ISSUE TITLE
Split codebase in crates

### ISSUE THREAD

**Issue by pvdrz** [pvdrz/pijama_legacy#88]
Even though the code is more or less well organized in modules. It would be more scalable moving each top level module into its own crate.

This would allow us to set clear API boundaries and dependencies between the different parts of the compiler and improve compilation time (although right now this isn't an issue).

These are the modules I consider we should migrate for now :
- [x] move the `ast` module to a `pijama_ast` crate (taken by @seanchen1991).
- [x] move the `parser` module to a `pijama_parse` crate.
- [ ] move the `mir::lower` module to a `pijama_ast_lower` crate.
- [x] move the rest of the `mir` module to a `pijama_mir` crate.
- [ ] move the `lir::lower` module to a `pijama_mir_lower` crate.
- [x] move the rest of the `lir` module to a `pijama_lir` crate.

It is not necessary to move them all at the same time but it should be a good idea to move them in the order they are in the checklist.

For each one of these items we need to:
- Create the new crate as a library under `./src/`.
- Include the new crate as a dependency for the top crate.
- Move the code from the module to the new crate's `src/` folder.
- Include the required external dependencies (at the top `Cargo.toml`) into the new crate's `Cargo.toml`
- Include the internal dependencies into the new crate's `Cargo.toml`
- Update the remaining code in `src` to `use` the new crate.

**Comment by DarkDrek** [comment]
Would we use this to support different implementations of evaluation lir and llama (#77)?

**Comment by pvdrz** [comment]
Yes, this would ease changes to any compilation stage.

We could even think about having different backends

**Comment by seanchen1991** [comment]
I’m always down to take any of the easy tasks :grin:

**Comment by pvdrz** [comment]
sure go ahead!

**Comment by seanchen1991** [comment]
Looks like I can't check anything off the checklist, or at least I'm not sure how. But we can mark the first task as done now 🙂 

I could go ahead and start working on migrating the parser out too unless there are more pressing issues.

**Comment by pvdrz** [comment]
I checked off the task from the list :)

Go ahead but maybe you should wait for https://github.com/christianpoveda/pijama/pull/91 to get merged before starting to avoid merge issues :P

Update: @seanchen1991 #91 got merged so you can start with the next module whenever you want :)

**Comment by DarkDrek** [comment]
In #95 the use of `Span` wasn't moved from `crate::parser::Span` to `pijama_ast::Span` it still compiles somehow??? with the wrong path but we should correct that.

Edit: Made a PR #104 to fix this. I still don't know why it compiles
