### ISSUE TITLE
Refactor evaluation

### ISSUE THREAD

**Issue by pvdrz** [pvdrz/pijama_legacy#9]
I realized on https://github.com/christianpoveda/pijama/issues/4 that evaluation needs to be rewritten in an scalable way. Right now there is too many interference between patterns in the `step` method inside the `lir.rs` module. 

For example, a term like `((+ t1) t2)` matches two different patterns and the behavior of the second pattern might depend on the first one. However, trying to change the patterns to be exhaustive makes them too long to be readable and just increases the size of the method.

I was thinking that maybe it is a good idea to abstract away the idea of evaluation rule to a trait like
```rust
trait EvalRule: Sized {
    // checks if term has the correct pattern and "creates" a rule from it
    fn create(term: &mut Term) -> Option<Self>;
    // consumes the rule and changes the term accordingly
    fn execute(self) -> EvalResult<()>;
    fn try_execute(term: &mut Term) -> Option<EvalResult<()>> {
        Self::create(term).map(Self::execute)
    }
}

impl Term {
    fn step(&mut self) -> EvalResult<()> {
        Rule1::try_execute(self)
            .or_else(|| Rule2::try_execute(self))
            .or_else(|| Rule3::try_execute(self))
            .unwrap_or_else(|| Err("No rule applies"))
    }
}
```
Edit: Following the idea in https://github.com/christianpoveda/pijama/issues/9#issuecomment-627743543, we can start migrating evaluation rules from the `step` method to a new `eval` module inside `lir`.
- [x] Beta reduction.
- [X] Conditionals (done in https://github.com/christianpoveda/pijama/pull/15).
- [ ] Fixed-point operator.
- [ ] Unary operators.
- [x] Binary operators. (@seanchen1991 do you want to take this and address https://github.com/christianpoveda/pijama/issues/4 at the same time?)

**Comment by pvdrz** [comment]
I've been thinking about this and using a trait might be a little bit over-engineered solution.

Maybe we could introduce simple functions like 
```rust
fn eval_binary_op(op: BinOp, t1: Term, t2: Term) -> (bool, Term) { ... }
```
And use them inside `step`
```rust
fn step(self) -> (bool, Term) {
    match self {
        App(box App(box Abs(Binary(op)), box t1), box t2) => eval_binary_op(op, t1, t2),
        ...
    }
}
```
In this way we shouldn't run into overlapping issues. However dead-code will become harder to detect if we don't document each rule properly.

Edit: When https://github.com/christianpoveda/pijama/pull/14 lands we will be able to write this in a more comfortable way.

**Comment by seanchen1991** [comment]
~~So you're saying to implement the `eval_binary_op` function in order to more cleanly implement the short-circuiting logic?~~ 

Oh, looks like you already implemented the `eval_bin_op` function in another PR. So we can just look into re-using that function for handling binary operator short-circuiting?

**Comment by pvdrz** [comment]
`eval_bin_op` does the "native" operation over literals, maybe we could rename it to `native_bin_op` and write a new function `step_bin_op` to compute the result of evaluating a term like `Term::BinaryOp(op, t1, t2)`. Something like
```rust
step_bin_op(op: BinOp, t1: Box<Term>, t2: Box<Term>) -> (bool, Term) {
    match (op, box t1, box t2) {
        (op, Term::Lit(l1), Term::Lit(l2) => // call native_bin_op,
        (BinOp::And, Term::Lit(Literal::False), _) => (true, Literal::False),
         ...
    }
}
```
And so on for the rest of the short-circuiting cases. And at the end we just need to dispatch `step_bin_op` inside `Term::step`.

Edit: I think you can take https://github.com/christianpoveda/pijama/pull/15 as a guide.

**Comment by pvdrz** [comment]
https://github.com/christianpoveda/pijama/pull/16 introduces some changes on how boolean literals are handled but the idea should be the same.
